name: iterminal
description: Cross-platform SSH terminal client MVP for Windows and future Android.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartssh2: ^2.13.0
  cryptography: ^2.7.0
  connectivity_plus: ^7.0.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.3
  xterm: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
